//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dogue.EF.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audition
    {
        public int AuditonID { get; set; }
        public int OwnerAssetID { get; set; }
        public string AuditionNotes { get; set; }
        public System.DateTime AuditionDate { get; set; }
        public string MediaType { get; set; }
        public string ContractingCompany { get; set; }
        public Nullable<bool> Successful { get; set; }
    
        public virtual OwnerAsset OwnerAsset { get; set; }
    }
}
