//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dogue.EF.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OwnerAsset()
        {
            this.Photos = new HashSet<Photo>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int OwnerAssetID { get; set; }
        public string AssetRegisteredName { get; set; }
        public string AssetCallName { get; set; }
        public string AssetSpecies { get; set; }
        public string AssetBreed { get; set; }
        public string AssetAge { get; set; }
        public string AssetSize { get; set; }
        public bool AssetTrainerCertified { get; set; }
        public string UserID { get; set; }
        public byte[] AssetPhoto { get; set; }
        public string SpecialNotes { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string DescriptiveColorProfile { get; set; }
    
        public virtual OwnerInformation OwnerInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
